---
# - name: Check posgresql status
#   command: systemctl is-active postgresql 
#   ignore_errors: true
#   register: postgresql_status


# - debug:
#     msg: "postgresql not installed. posgresql status : {{ postgresql_status }}"
#   when: postgresql_status.rc != 0


# - name: Stop role execution if postgres is running
#   meta: end_play
#   when: postgresql_status.rc == 0


- name: Install dependencies
  package:
    name: "{{ item.name }}"
    state: present
  loop: "{{ dependencies }}"


- name: Initialize database
  command: postgresql-setup --initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION
  register: init_db_status


- name: Print db initialization status
  debug: 
    msg: "db initialization : {{ init_db_status }}"


- name: Fail if db not initialized
  fail:
    msg: "DB not initialized successfully"
  when: init_db_status.rc != 0


- name: Start and enable database
  service:
    name: postgresql
    state: started
    enabled: true


- name: Check db initialized 
  command: systemctl is-active postgresql 
  ignore_errors: true
  register: db_active_status


- name: Fail if db not active
  fail:
    msg: "Db not active"
  when: db_active_status.rc != 0


- name: Check db enabled 
  command: systemctl is-enabled postgresql 
  ignore_errors: true
  register: db_enable_status


- name: Fail if db not enabled
  fail:
    msg: "Db not enabled"
  when: db_enable_status.rc != 0


- name: Create database user
  become_user: postgres 
  command: createuser "{{ db_user_name }}"
  register: db_username_status
  failed_when: db_username_status.rc != 0 and 'already exists' not in db_username_status.stderr
  changed_when: db_username_status.rc == 0

- name: Check if database user exists 
  become_user: postgres
  command: psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='{{ db_user_name }}'"
  register: db_user_validation_status
  changed_when: false

- name: Assert user exists
  assert:
    that: "'1' in db_user_validation_status.stdout"
    fail_msg: "User {{ db_user_name }} was not created"
    success_msg: "User {{ db_user_name }} creation confirmed"
  

- name: Set password for database user 
  become_user: postgres 
  command: psql -c "ALTER USER {{ db_user_name }} WITH PASSWORD '{{ db_user_pw }}';"
  register: db_userpw_status
  failed_when: db_userpw_status.rc != 0
  changed_when: db_userpw_status.rc == 0


- name: Create database 
  become_user: postgres
  command: createdb -O "{{ db_user_name }}" "{{ db_name }}"
  register: db_status 
  failed_when: db_status.rc != 0 and 'already exists' not in db_status.stderr 
  changed_when: db_status.rc == 0


- name: Check if database exits 
  become_user: postgres
  command: psql -tAc "SELECT 1 FROM pg_database WHERE datname='{{ db_name }}'"
  register: db_validation_status
  changed_when: false 

- name: Assert databse exists 
  assert:
    that: "'1' in db_validation_status.stdout"
    fail_msg: "Database {{ db_name }} was not created"
    success_msg: "Database {{ db_name }} creation confirmed"


- name: Update listen_addresses
  lineinfile:
    path: /var/lib/pgsql/data/postgresql.conf
    regexp: "^#?listen_addresses\\s*="
    line: "listen_addresses = '{{ db_node_ip }}'          # what IP address(es) to listen on;"
  notify: restart postgresql

- name: Check if listen_addresses Update
  command: grep "listen_addresses = '{{ db_node_ip }}'" /var/lib/pgsql/data/postgresql.conf
  register: listen_addresses_validation_status
  changed_when: false 


- name: Assert listen_addresses updated
  assert:
    that: "listen_addresses_validation_status.rc == 0"
    fail_msg: "listen_addresses not updated to {{ db_node_ip }}"
    success_msg: "listen_addresses updated to {{ db_node_ip }} confirmed"

 
- name: Add pg_hpa entries for app servers
  blockinfile:
    path: /var/lib/pgsql/data/pg_hba.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK - For {{ db_name }} db access to app servers"
    block: |
      host    infomarket    infomarket    {{ app01_node_ip }}/32    scram-sha-256
      host    infomarket    infomarket    {{ app02_node_ip }}/32    scram-sha-256


- name: Update password encryption type to SCRAM
  become_user: postgres
  command: psql -c "ALTER SYSTEM SET password_encryption = 'scram-sha-256';"
  register: db_userpw_encypted_status
  failed_when: db_userpw_encypted_status.rc != 0
  changed_when: db_userpw_encypted_status.rc == 0
  notify: reload postgresql

- name: Reset password for database user 
  become_user: postgres 
  command: psql -c "ALTER USER {{ db_user_name }} WITH PASSWORD '{{ db_user_pw }}';"
  register: db_userpw_status
  failed_when: db_userpw_status.rc != 0
  changed_when: db_userpw_status.rc == 0


- name: Check password encryption type for database user 
  become_user: postgres
  command: psql -tAc "SELECT LEFT(rolpassword, 4) FROM pg_authid WHERE rolname='{{ db_user_name }}';"
  register: password_type_check
  changed_when: false

- name:  Assert password encryption is SCRAM 
  assert:
    that: "password_type_check.stdout.strip() == 'SCRA'"
    fail_msg: "Password for {{ db_user_name }} is not SCRAM-encrypted (got: {{ password_type_check.stdout }})"
    success_msg: "Password for {{ db_user_name }} confirmed SCRAM-encrypted"









