---

- name: Install dependencies
  package:
    name: "{{ item.name }}"
    state: present
  loop: "{{ dependencies }}"


- name: Clone git repo
  git: 
    repo: "{{ git_repo_url }}"
    dest: /home/vagrant/flask-postgresql-project


- name: Check if git repo cloned 
  stat:
    path: /home/vagrant/flask-postgresql-project
  register: git_repo_status


- name: Assert repo cloned 
  assert:
    that: 
      - git_repo_status.stat.exists
      - git_repo_status.stat.isdir
    fail_msg: "Git repo was not cloned"
    success_msg: "Git repo cloned successfully"


- name: Install backend dependencies
  command: pip3 install --user -r requirements.txt
  args:
    chdir: /home/vagrant/flask-postgresql-project/backend
  register: requirement_installation_status
  failed_when: requirement_installation_status.rc != 0
  changed_when: requirement_installation_status.rc == 0


- name: Assert backend dependencies installed
  assert:
    that: "requirement_installation_status.rc == 0"
    fail_msg: "Required all backend dependencies not installed"
    success_msg: "All required backend dependencies installed"


- name: Print backend dependencies install failure status 
  debug:
    msg: "Failure Status: {{ requirement_installation_status.stderr }}"
  when: requirement_installation_status.rc != 0


- name: Prepare backend environment file
  copy:
    dest: /home/vagrant/flask-postgresql-project/backend/.env
    content: |
      APP_SETTINGS={{ backend_env_app_setting }}
      DATABASE_URL={{ backend_env_db_url }}
      API_HOST={{ ansible_host }}
      API_PORT={{ backend_env_api_port }}
    owner: vagrant
    group: vagrant
    mode: '0644'


- name: Start the backend
  become: false
  shell: |
    nohup gunicorn --chdir backend --bind 0.0.0.0:{{ backend_env_api_port }} app:app > backend/backend.log 2>&1 &
    echo $!
  args:
    chdir: /home/vagrant/flask-postgresql-project/
  environment:
    PATH: "/home/vagrant/.local/bin:{{ ansible_env.PATH }}"
  register: backend_status


- name: Show backend process status 
  debug:
    msg: "Backend process : {{ backend_status }}"


- name: Verify backend port accessable
  wait_for: 
    host: 127.0.0.1
    port: "{{ backend_env_api_port }}"
    timeout: 20


- name: Start the frontend
  become: false
  become_user: vagrant
  shell: | 
    nohup python -m http.server {{ frontend_api_port }} --directory frontend > frontend/frontend.log 2>&1 &
    echo $!
  args:
    chdir: /home/vagrant/flask-postgresql-project/
  register: frontend_status


- name: Show frontend process 
  debug:
    msg: "frontend process : {{ frontend_status }}"


- name: Verify frontend port accessable
  wait_for: 
    host: "{{ ansible_host }}"
    port: "{{ frontend_api_port }}"
    timeout: 20