---
- name: Install dependencies
  package:
    name: "{{ item.name }}"
    state: present
  loop: "{{ dependencies }}"


- name: Clone git repo
  become: false
  become_user: vagrant
  git: 
    repo: "{{ git_repo_url }}"
    dest: /home/vagrant/flask-postgresql-project
    force: true


- name: Check if git repo cloned 
  stat:
    path: /home/vagrant/flask-postgresql-project
  register: git_repo_status


- name: Assert repo cloned 
  assert:
    that: 
      - git_repo_status.stat.exists
      - git_repo_status.stat.isdir
    fail_msg: "Git repo was not cloned"
    success_msg: "Git repo cloned successfully"


- name: Install backend dependencies
  become: false
  become_user: vagrant
  command: pip3 install --user -r requirements.txt
  args:
    chdir: /home/vagrant/flask-postgresql-project/backend
  register: requirement_installation_status
  failed_when: requirement_installation_status.rc != 0
  changed_when: requirement_installation_status.rc == 0


- name: Print requirement installation status
  debug:
    var: requirement_installation_status


- name: Assert backend dependencies installed
  assert:
    that: "requirement_installation_status.rc == 0"
    fail_msg: "Required all backend dependencies not installed"
    success_msg: "All required backend dependencies installed"


- name: Print backend dependencies install failure status 
  debug:
    msg: "Failure Status: {{ requirement_installation_status.stderr }}"
  when: requirement_installation_status.rc != 0


- name: Set SELinux context for gunicorn binary
  sefcontext:
    target: /home/vagrant/.local/bin/gunicorn
    setype: bin_t


- name: Restore SELinux context 
  command: restorecon -v /home/vagrant/.local/bin/gunicorn


- name: Prepare backend environment file
  copy:
    dest: /home/vagrant/flask-postgresql-project/backend/.env
    content: |
      APP_SETTINGS={{ backend_env_app_setting }}
      DATABASE_URL={{ backend_env_db_url }}
      API_HOST={{ ansible_host }}
      API_PORT={{ backend_env_api_port }}
    owner: vagrant
    group: vagrant
    mode: '0644'


- name: Initialize one time migration
  become: false
  become_user: vagrant
  command: python3 manage.py db init
  args:
    chdir: /home/vagrant/flask-postgresql-project/backend
    creates: /home/vagrant/flask-postgresql-project/backend/migrations
  when: inventory_hostname == 'app01'


- name: check if migration scripts exists
  find:
    paths: /home/vagrant/flask-postgresql-project/backend/migrations/versions
    patterns: "*.py"
  register: migration_scripts
  when: inventory_hostname == 'app01'


- name: Generate one time initial migration
  become: false
  become_user: vagrant
  command: python3 manage.py db migrate -m "initial migration"
  args:
    chdir: /home/vagrant/flask-postgresql-project/backend
  when:
  - inventory_hostname == 'app01'
  - migration_scripts.matched == 0


- name: Apply one time database migration 
  become: false
  become_user: vagrant
  command: python3 manage.py db upgrade
  args:
    chdir: /home/vagrant/flask-postgresql-project/backend
  register: db_upgrade_status
  changed_when: "'Running upgrade' in db_upgrade_status.stdout"
  when: inventory_hostname == 'app01'


- name: Deploy the backend systemd service file 
  template:
    src: flask_backend.service.j2
    dest: /etc/systemd/system/flask_backend.service
  notify: reload daemon


- name: Flush handlers to apply reload daemon immediately
  meta: flush_handlers


- name: Start and enable backend service 
  systemd:
    name: flask_backend
    state: started 
    enabled: true 

- name: Verify backend port accessable
  wait_for: 
    host: 127.0.0.1
    port: "{{ backend_env_api_port }}"
    timeout: 10


- name: Deploy the frontend systemd service file 
  template:
    src: flask_frontend.service.j2
    dest: /etc/systemd/system/flask_frontend.service
  notify: reload daemon


- name: Flush handlers to apply reload daemon immediately
  meta: flush_handlers


- name: Start and enable frontend service 
  systemd:
    name: flask_frontend
    state: started 
    enabled: true 


- name: Verify frontend port accessable
  wait_for: 
    host: "{{ ansible_host }}"
    port: "{{ frontend_api_port }}"
    timeout: 10